name: Install VS Code
description: Set up VS Code (Linux-only)
author: Marten Lohstroh <marten@berkeley.edu>

runs:
  using: composite
  steps:
    - name: Install VS Code
      run: |
        sudo apt update
        sudo apt install software-properties-common apt-transport-https wget
        wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
        sudo apt install code
      shell: bash