name: Build

on:
  workflow_call:
    inputs:
      partial:
        required: false
        default: true
        type: boolean

jobs:
  build:
    steps:
      - name: Set up Java 17
        run: |
          echo "$JAVA_HOME_17_X64/bin" >> $GITHUB_PATH
          echo "org.gradle.java.home=${JAVA_HOME_17_X64//\\/\/}" >> gradle.properties
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
        shell: bash
      - name: Check settings
        run: |
          echo $(which java)
          cat gradle.properties
          echo $JAVA_HOME
        shell: bash
      - name: Build the VS Code extension
        run: npm install --ignore-scripts
        shell: bash
      - name: Install pylint
        run: python3 -m pip install pylint
        shell: bash
      - name: Install pnpm
        run: npm i -g pnpm
        shell: bash
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy
      - name: Install RTI
        run: |
          cd lingua-franca
          .github/actions/install-rti/install.sh
          cd ..
        shell: bash
        if: ${{ runner.os == 'macOS' || runner.os == 'Linux' }}
