# Main workflow for testing the Lingua Franca Visual Studio Code Extension 
name: CI

on:
  # Trigger this workflow on push events, but only on master.
  push:
    branches:
      - main
  # Trigger this workflow also on pull_request events.
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        rust: [nightly]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out vscode-lingua-franca repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 1
      - name: Build the extension
        uses: ./.github/actions/build
      - name: Run tests (Linux)
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test
        if: ${{ runner.os == 'Linux' }}
      - name: Run tests (non-Linux)
        run: npm run test
        if: ${{ runner.os != 'Linux' }}
