# Workflow for testing check for dependencies in the Lingua Franca VS Code Extension
name: Test dependency checks

on:
  # Trigger this workflow on push events, but only on main.
  push:
    branches:
      - main
    paths:
      - "**/check_dependencies.ts"
      - "**/version_checker.ts"
      - "**/version.ts"
  # Trigger this workflow also on pull_request events.
  pull_request:
    paths:
      - "**/check_dependencies.ts"
      - "**/version_checker.ts"
      - "**/version.ts"

jobs:
  test-dependencies-outdated:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out vscode-lingua-franca repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 1
      - name: Build the extension
        uses: ./.github/actions/build
        with:
          partial: true
      - name: Uninstall dependencies
        run: |
          PIP_BREAK_SYSTEM_PACKAGES=1 python3 -m pip uninstall -y pylint
      - name: Downgrade dependencies
        run: |
          pip install -I pylint==2.10.0
      - name: Run tests (Linux)
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test-dependencies-outdated
        if: ${{ runner.os == 'Linux' }}
      - name: Run tests (non-Linux)
        run: npm run test-dependencies-outdated
        if: ${{ runner.os != 'Linux' }}
  test-dependencies-missing-extended:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out vscode-lingua-franca repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 1
      - name: Build the extension
        uses: ./.github/actions/build
        with:
          partial: true
      - name: Uninstall dependencies
        run: |
          PIP_BREAK_SYSTEM_PACKAGES=1 python3 -m pip uninstall -y pylint
      - name: Run tests (Linux)
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test-dependencies-missing-extended
        if: ${{ runner.os == 'Linux' }}
      - name: Run tests (non-Linux)
        run: npx --yes cross-env LF_VS_CODE_ALLOW_GLOBAL_UNINSTALLS=OK npm run test-dependencies-missing-extended
        if: ${{ runner.os != 'Linux' }}
  test-dependencies-missing-basic:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out vscode-lingua-franca repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 1
      - name: Build the extension
        uses: ./.github/actions/build
        with:
          partial: true
      - name: Run tests (Linux)
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test-dependencies-missing-basic
        if: ${{ runner.os == 'Linux' }}
      - name: Run tests (non-Linux)
        run: npx --yes cross-env LF_VS_CODE_ALLOW_GLOBAL_UNINSTALLS=OK npm run test-dependencies-missing-basic
        if: ${{ runner.os != 'Linux' }}
