# Main workflow for testing the Lingua Franca Visual Studio Code Extension
name: CI

on:
  # Trigger this workflow on push events, but only on main.
  push:
    branches:
      - main
    paths:
      - '**/check_dependencies.ts'
      - '**/version_checker.ts'
      - '**/version.ts'
  # Trigger this workflow also on pull_request events.
  pull_request:
    paths:
    - '**/check_dependencies.ts'
    - '**/version_checker.ts'
    - '**/version.ts'

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        rust: [nightly]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: lf-lang/vscode-lingua-franca/.github/actions/build@update-error-message
  test-dependencies-outdated:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: lf-lang/vscode-lingua-franca/.github/actions/build@update-error-message
      - name: Downgrade dependencies
        run: |
          pip install -I pylint==2.10.0
          rustup default 1.26.0
      - name: Run tests (Linux)
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test-dependencies-outdated
        if: ${{ runner.os == 'Linux' }}
      - name: Run tests (non-Linux)
        run: npm run test-dependencies-outdated
        if: ${{ runner.os != 'Linux' }}
  test-dependencies-missing-extended:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: lf-lang/vscode-lingua-franca/.github/actions/build@update-error-message
      - name: Run tests (Linux)
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test-dependencies-missing-extended
        if: ${{ runner.os == 'Linux' }}
      - name: Run tests (non-Linux)
        run: npm run test-dependencies-missing-extended
        if: ${{ runner.os != 'Linux' }}
  test-dependencies-missing-basic:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: lf-lang/vscode-lingua-franca/.github/actions/build@update-error-message
      - name: Run tests (Linux)
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test-dependencies-missing-basic
        if: ${{ runner.os == 'Linux' }}
      - name: Run tests (non-Linux)
        run: npm run test-dependencies-missing-basic
        if: ${{ runner.os != 'Linux' }}
