name: Nightly build

# Trigger the workflow every day at 5 AM (UTC).
on:
  push:
    branches: nightly
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out vscode-lingua-franca repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 1
      - name: Pull the latest lingua-franca submodule
        run: |
          git checkout master
          git pull
          git submodule update --init --recursive
        working-directory: vscode-lingua-franca/lingua-franca
      - name: Set nightly version number
        run: |
          ./.github/scripts/nightly-version.sh
      - name: Build the extension
        uses: ./.github/actions/build
      - name: Report status
        run: |
          ls -l
          git status
